name: Main Workflow

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    name: "Build Node App"
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:6.0.16-rc0
        ports:
          - 27017:27017

      redis:
        image: redis:6.2.6
        ports:
          - 6379:6379

    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          npm ci

      - name: Setup Env
        run: |
          cp .env.ci .env

      # - name: Start The App
      #   run: |
      #     npm start

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          repository: kaungmyatsoedev/wops-node
          tags: latest
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
